-- Создание таблицы статей
CREATE TABLE articles (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  text TEXT NOT NULL
);

-- Создание таблицы комментариев
CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  text TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  article_id INT REFERENCES articles(id) ON DELETE CASCADE
);

-- Вставка данных в таблицу статей
INSERT INTO articles (title, text) VALUES
('Article 1', 'This is the text of article 1.'),
('Article 2', 'This is the text of article 2.'),
('Article 3', 'This is the text of article 3.'),
('Article 4', 'This is the text of article 4.'),
('Article 5', 'This is the text of article 5.'),
('Article 6', 'This is the text of article 6.'),
('Article 7', 'This is the text of article 7.'),
('Article 8', 'This is the text of article 8.'),
('Article 9', 'This is the text of article 9.'),
('Article 10', 'This is the text of article 10.');

-- Вставка данных в таблицу комментариев (по 10 комментариев для каждой статьи)
INSERT INTO comments (text, rating, article_id) VALUES
('Great article 1', 5, 1),
('Interesting points in article 1', 4, 1),
('Helpful content in article 1', 5, 1),
('Could improve in article 1', 3, 1),
('Well-written article 1', 5, 1),
('Not what I expected from article 1', 2, 1),
('I learned a lot from article 1', 5, 1),
('Engaging read in article 1', 4, 1),
('Article 1 was too short', 3, 1),
('Outstanding article 1', 5, 1),

('Nice insights in article 2', 4, 2),
('Article 2 could be clearer', 3, 2),
('Really enjoyed article 2', 5, 2),
('Helpful tips in article 2', 4, 2),
('Needs more depth in article 2', 2, 2),
('Great examples in article 2', 5, 2),
('I loved article 2', 5, 2),
('Not as expected from article 2', 3, 2),
('Very informative article 2', 5, 2),
('Solid read in article 2', 4, 2),

('Informative article 3', 5, 3),
('Article 3 could be better', 3, 3),
('Great structure in article 3', 5, 3),
('Missing some details in article 3', 3, 3),
('Easy to follow article 3', 4, 3),
('Engaging content in article 3', 5, 3),
('Could be more concise in article 3', 3, 3),
('Interesting perspectives in article 3', 4, 3),
('Article 3 was enjoyable', 5, 3),
('Loved the conclusion of article 3', 5, 3),

('I found article 4 useful', 4, 4),
('Solid advice in article 4', 5, 4),
('Needs improvement in article 4', 3, 4),
('Clear writing in article 4', 4, 4),
('I liked article 4', 5, 4),
('Not enough detail in article 4', 2, 4),
('Article 4 has potential', 3, 4),
('Well-researched article 4', 5, 4),
('More examples needed in article 4', 3, 4),
('Good summary in article 4', 4, 4),

('Good article 5', 3, 5),
('Interesting angle in article 5', 4, 5),
('Thorough research in article 5', 5, 5),
('Article 5 was confusing at times', 2, 5),
('Nice explanation in article 5', 4, 5),
('I disagree with article 5', 2, 5),
('Clear points in article 5', 4, 5),
('Good read overall in article 5', 5, 5),
('More detail needed in article 5', 3, 5),
('Solid conclusion in article 5', 4, 5),

('Well-written article 6', 5, 6),
('Could use more sources in article 6', 3, 6),
('Engaging content in article 6', 5, 6),
('Not enough depth in article 6', 2, 6),
('Strong arguments in article 6', 4, 6),
('I enjoyed reading article 6', 5, 6),
('Article 6 could be shorter', 3, 6),
('Great analysis in article 6', 5, 6),
('Helpful examples in article 6', 4, 6),
('I recommend article 6', 5, 6),

('Article 7 could be better', 3, 7),
('Good points in article 7', 4, 7),
('Too much information in article 7', 2, 7),
('Clear and concise article 7', 4, 7),
('Well-researched article 7', 5, 7),
('More visuals needed in article 7', 3, 7),
('I enjoyed reading article 7', 5, 7),
('Could be more concise in article 7', 3, 7),
('Informative article 7', 4, 7),
('Good structure in article 7', 5, 7),

('I enjoyed article 8', 5, 8),
('Article 8 was well-written', 4, 8),
('Could use more depth in article 8', 3, 8),
('Helpful article 8', 5, 8),
('I expected more from article 8', 2, 8),
('Good use of examples in article 8', 4, 8),
('Clear writing in article 8', 5, 8),
('More research needed in article 8', 3, 8),
('Enjoyed reading article 8', 5, 8),
('Solid argumentation in article 8', 4, 8),

('Article 9 was okay', 4, 9),
('I learned a lot from article 9', 5, 9),
('Could be more detailed in article 9', 3, 9),
('Nice flow in article 9', 4, 9),
('Too technical for me in article 9', 2, 9),
('Clear explanations in article 9', 5, 9),
('Well-organized article 9', 4, 9),
('Needs improvement in article 9', 3, 9),
('I enjoyed article 9', 5, 9),
('Strong conclusion in article 9', 5, 9),

('Excellent article 10', 5, 10),
('Clear and informative article 10', 5, 10),
('I found article 10 useful', 4, 10),
('Could use more visuals in article 10', 3, 10),
('Well-researched article 10', 5, 10),
('Great summary in article 10', 4, 10),
('Not enough depth in article 10', 3, 10),
('Article 10 was very insightful', 5, 10),
('Good explanation in article 10', 4, 10),
('Interesting perspectives in article 10', 5, 10);
